http_server:
  address: ":8080"
  read_timeout: 5s
  write_timeout: 5s
  idle_timeout: 30s

postgres:
  host: storage
  port: 5432
  user: postgres
  password: password
  db_name: shop

logger:
  level: debug
  format: json